language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "iojs"
env:
  global:
    - secure: O9iJfZef2HUSIE0Qm8WiN6athn5SxPIpFEiHfk1VoD0g2hqqQxPJEcOXaEkn7bBQIH2BE6/J20/j3nZqpXci1cajvSdbHORrXgm2qi4TkamxuuyAlCen/4+RlT21bZlTda1ZWTC049CdNobkkI8oL44r1OWMaXEodl4vkIHi+ig=
    - secure: fm4y+uk3/w8KGn85ZDgWww5SgGkXRKTurSgyhGOGgtegUaNvTY/J1blOZiIlzDwPDiKs5QWsRS1kbE22FiKyyOmgzjR0DH8aZuqkJXgj7Gej+UgCXtzhFi+YoPiLg02lt+2EjAm9Vkg8TWoH1s1xZuHRMIH8LLPxDZ+/zwc0kBY=
